{
  imports = [
    ./catppuccin
    ./nvim-surround
    ./oil
    ./conform
    ./lualine
    ./nvim-cmp
    ./telescope
    ./todo-comments
    ./nvim-autopairs
    ./nvim-lspconfig
    ./nvim-treesitter
    ./indent-blankline
    ./dressing
    ./toggleterm
    ./nvim-lint
    ./gitsigns
    ./comment
    ./luasnip
    ./neogit
    ./copilot
    ./nvim-dap
  ];
}
