{
  imports = [
    ./catppuccin
    ./nvim-treesitter
    ./nvim-lspconfig
    ./nvim-dap
    ./conform
    ./nvim-lint
    ./nvim-cmp
    ./nvim-autopairs
    ./nvim-surround
    ./lualine
    ./oil
    ./indent-blankline
    ./gitsigns
    ./telescope
    ./comment
    ./todo-comments
    ./dressing
    ./fidget
    ./toggleterm
  ];
}
